// Generated by CoffeeScript 1.7.1
(function() {
  var R;

  R = require('requirejs');

  R.config({
    nodeRequire: require
  });

  R.define('foo', [], function() {
    console.log('foo', arguments);
    return {};
  });

  R.define('bar', [], function() {
    console.log('bar', arguments);
    return {};
  });

  R(['foo', 'bar'], function(foo, bar) {
    return console.log(foo, bar);
  });

  R.define('c', [], function() {});

  R.define('skirt', {
    color: 'black',
    size: 'unsize'
  });

  R.define('skirt2', function() {
    return {
      color: 'black',
      size: 'unsize'
    };
  });

  R.define('cart', {
    name: 'cart'
  });

  R.define('inventory', function() {
    return {
      name: 'inventory'
    };
  });

  R.define('skirt3', ['cart', 'inventory'], function(cart, inventory) {
    return {
      name: cart.name + ', ' + inventory.name,
      color: 'blue',
      size: 'large'
    };
  });

  R(['skirt3'], function(skirt) {
    return console.log(skirt);
  });

}).call(this);
